// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3Omy2zyTHPMH5sh_erhCeDGBzjfZBtHg',
    appId: '1:514802340661:web:268e3b164d603de3f3b27c',
    messagingSenderId: '514802340661',
    projectId: 'myportfolio-1ace9',
    authDomain: 'myportfolio-1ace9.firebaseapp.com',
    storageBucket: 'myportfolio-1ace9.firebasestorage.app',
    measurementId: 'G-2ZRBN96KZG',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBvff11wL7ta8NEiChW_LOFooyLgDYQFt0',
    appId: '1:514802340661:ios:991774f1f08c0ce5f3b27c',
    messagingSenderId: '514802340661',
    projectId: 'myportfolio-1ace9',
    storageBucket: 'myportfolio-1ace9.firebasestorage.app',
    iosBundleId: 'com.example.myPortfolio',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvff11wL7ta8NEiChW_LOFooyLgDYQFt0',
    appId: '1:514802340661:ios:991774f1f08c0ce5f3b27c',
    messagingSenderId: '514802340661',
    projectId: 'myportfolio-1ace9',
    storageBucket: 'myportfolio-1ace9.firebasestorage.app',
    iosBundleId: 'com.example.myPortfolio',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8OccZRWji2ahGISC7J4GbDNTz5SczUtg',
    appId: '1:514802340661:android:e4b77db8b42eb6c0f3b27c',
    messagingSenderId: '514802340661',
    projectId: 'myportfolio-1ace9',
    storageBucket: 'myportfolio-1ace9.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA3Omy2zyTHPMH5sh_erhCeDGBzjfZBtHg',
    appId: '1:514802340661:web:aa49617836ab9f12f3b27c',
    messagingSenderId: '514802340661',
    projectId: 'myportfolio-1ace9',
    authDomain: 'myportfolio-1ace9.firebaseapp.com',
    storageBucket: 'myportfolio-1ace9.firebasestorage.app',
    measurementId: 'G-RMBC3XSZ6V',
  );

}